export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  GENDER_REVEL: "gender-revel",
  NATIONALIZE: "nationalize",
  COUNER: "counter",
  SPACE_MISSION: "space-mission",
  PROFILE: "profile",
  PROFILE_DATA: "/profile/data",
  PROFILE_SETTINGS: "/profile/settings",
  PRODUCT_PAGE: (id: number | string) => `/products/${id}`,
  USERS_LIST: "users",
  USER_PAGE: "users/:id",
  CAR_PAGE: "cars/:carModel",
  NOTFOUND: "*",
  SIGNUP: "signup",
  PRODUCT_LIST: "Productlist",
  SIGNIN: "signin",
  CREATE_CATEGORY: "categories/create",
} as const;
